[phases.setup]
# כאן הוספנו את ffmpeg ואת nodejs כדי לפתור את שתי השגיאות שראית
nixPkgs = ["python311", "ffmpeg", "nodejs_20"]

[phases.build]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"
